# Generated by Django 5.2.3 on 2025-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quarto', models.IntegerField()),
                ('andar_quarto', models.IntegerField()),
                ('status_quarto', models.CharField(verbose_name=45)),
                ('preco_diaria_quarto', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
