# Generated by Django 5.2.4 on 2025-07-04 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('idServico', models.UUIDField(default=uuid.UUID('ad57023d-bcf1-4246-b40d-cc1f5791ecce'), editable=False, primary_key=True, serialize=False)),
                ('nome_Servico', models.CharField(max_length=45)),
            ],
        ),
    ]
