# Generated by Django 5.2.4 on 2025-07-04 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0002_serviço'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='serviço',
            name='idServico',
            field=models.UUIDField(default=uuid.UUID('3a8bc15c-3a95-451f-9b0e-4772698b95e0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
