# Generated by Django 5.2.4 on 2025-07-05 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0003_pagamento_alter_serviço_idservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quarto', models.IntegerField()),
                ('andar_quarto', models.IntegerField()),
                ('status_quarto', models.CharField(verbose_name=45)),
                ('preço_diaria_quarto', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='serviço',
            name='idServico',
            field=models.UUIDField(default=uuid.UUID('3205f430-28cf-410a-be2f-fda6712cd0f4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
