# Generated by Django 5.2.4 on 2025-07-05 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria', '0004_quarto_alter_serviço_idservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.IntegerField(primary_key=True, serialize=False)),
                ('email_funcionario', models.CharField(max_length=45)),
                ('salario_funcionario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Servicos_pk_idServicos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('pk_idServicos', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='serviço',
            name='idServico',
            field=models.UUIDField(default=uuid.UUID('e8d6da53-8340-4555-ba25-72f53f930466'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reserva_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelaria.reserva')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelaria.serviço')),
            ],
        ),
    ]
